1) SELECT DISTINCT u.* FROM `UTENTI` u, `PRODOTTI` p, `RECENSIONI` r WHERE 50<=(2019-u.ANNO_NASCITA) and u.ID=r.UTENTE and r.PRODOTTO=p.ID and p.categoria="Elettrodomestici"
2) SELECT COUNT(*) as Totale_rec FROM `RECENSIONI` r, `UTENTI` u WHERE u.NOME="Conti" and u.COGNOME="Novellina" and u.ID=r.UTENTE and r.VOTO>2
3) SELECT COUNT(r.ID) as nrec, AVG(r.VOTO) as mvoti, MIN(r.VOTO) as minvoto, MAX(r.VOTO) as maxvoto FROM `RECENSIONI` r WHERE r.PRODOTTO="24"
4) CREATE VIEW au2013 as SELECT u.*, p.DESCRIZIONE FROM `UTENTI` u, `PRODOTTI` p, `ACQUISTI` a WHERE u.ID=a.UTENTE and a.PRODOTTO=p.ID and a.DATA > '2013-01-01'
5)
6) SELECT DISTINCT u.* FROM `UTENTI` u, `RECENSIONI` r WHERE u.ID=r.UTENTE and r.VOTO=5 and u.CITTA="Messina"
7) SELECT DISTINCT p.* FROM `PRODOTTI` p WHERE 3>=ALL(SELECT r.VOTO FROM `RECENSIONI` r WHERE r.PRODOTTO=p.ID)
8) SELECT DISTINCT p.* FROM `PRODOTTI` p WHERE p.PREZZO>100 and "Francese"=ALL(SELECT u.NAZIONALITA FROM `UTENTI` u, `RECENSIONI` r WHERE u.ID=r.UTENTE and r.PRODOTTO=p.ID)
9) 
